import { SongItem } from "@/modules/apps/SongItem";
import { Layout } from "@/modules/shareds/Layout";
import { api } from "@/utils/api";
import Head from "next/head";

export default function Home() {
  const { data } = api.songs.search.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="grid grid-cols-3 gap-5">
          {data?.songs
            .slice(0, 100)
            .map((song) => <SongItem {...song} key={song.id} />)}
        </div>
      </Layout>
    </>
  );
}
